### ISSUE TITLE
File Object (FileModel) doesn't return file_id

### ISSUE THREAD

**Issue by shalltell** [lokalise/python-lokalise-api#108]
**Describe the bug**
FileModel doesn't return file_id

**To Reproduce**
```files = client.files(project.project_id)```

**Expected behavior**
FileModel to contain files.items which contains `filename`, `key_count` along with `file_id`

**Your environment:**
Unix + Python

**Additional context**

**Comment by bodrovis** [comment]
I'll release a new version shortly :)
