### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [lokalise/python-lokalise-api#118]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in a Lokalise CloudQuery plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Lokalise data to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by bodrovis** [comment]
Good day! Thank you for reaching out to us :) I'll consult with the team and let you know asap

**Comment by bodrovis** [comment]
Unfortunately, we can't maintain it :(  We encourage the community to reach out to open-source contributors who may be willing to take on maintenance. We are open to featuring Lokalise CloudQuery plugin on our developer portal though!
