### ISSUE TITLE
Invalid type hints for `params` in `create_webhook` and `update_webhook`

### ISSUE THREAD

**Issue by Toreno96** [lokalise/python-lokalise-api#149]
**Describe the bug**

It is defined in https://github.com/lokalise/python-lokalise-api/blob/37f2a7dad7c1034d8d29b4d1796327fad73d8611/lokalise/client.py#L1488-L1490 and
https://github.com/lokalise/python-lokalise-api/blob/37f2a7dad7c1034d8d29b4d1796327fad73d8611/lokalise/client.py#L1501-L1502
as `[Dict[str, str]]`, but one of possible params (and required in the case of `create_webhook`) is `events`, which according to the docs should be an array of strings:
https://developers.lokalise.com/reference/create-a-webhook
https://python-lokalise-api.readthedocs.io/en/v2.1.1/api/webhooks.html#create-webhook

This causes a false positive in type checkers, e.g. in PyCharm:
<img width="616" alt="2023-08-08_16-29-33_CEST_screenshot" src="https://github.com/lokalise/python-lokalise-api/assets/16722326/b1553e9b-ea50-4717-8f2d-8559f6db94e4">

**To Reproduce**
1. Call `create_webhook` and `update_webhook` with parameter `events`.
2. Run a type checker on the code (e.g. PyCharm's built-in one or mypy, or others).

**Expected behavior**
No error from a type checker.

**Your environment:**
n/a

**Additional context**
n/a

**Comment by bodrovis** [comment]
A PR to fix this very much welcome! If that's not possible I'll look into it in the next few days
