### ISSUE TITLE
Catalan lang_iso is not recognized by API 

### ISSUE THREAD

**Issue by mathieudebrito** [lokalise/python-lokalise-api#15]
**Describe the bug**
I use the python-lokalise-api to upload my app's translations files. I works fine for most of the languages, but when it comes to catalan, it fails with the following error : 

```
 File "/usr/local/lib/python3.9/site-packages/lokalise/client.py", line 375, in upload_file
    raw_process = self.get_endpoint("files"). \
  File "/usr/local/lib/python3.9/site-packages/lokalise/endpoints/files_endpoint.py", line 26, in upload
    return request.post(self.client, path + '/upload', params)
  File "/usr/local/lib/python3.9/site-packages/lokalise/request.py", line 53, in post
    return respond_with(requests.post(__prepare(BASE_URL + path),
  File "/usr/local/lib/python3.9/site-packages/lokalise/request.py", line 114, in respond_with
    respond_with_error(data, response.status_code)
  File "/usr/local/lib/python3.9/site-packages/lokalise/request.py", line 129, in respond_with_error
    raise errors.ERROR_CODES[code](msg, code)
lokalise.errors.BadRequest: ('Unknown `lang_iso`', 400)
```

**To Reproduce**
here is the code I use : 
```python

    file_content = io.open(my_file_path, mode="r", encoding="utf-8").read()
    base64_encoded_file_content_as_bytes = base64.b64encode(file_content.encode('utf-8'))
    base64_encoded_file_content = base64_encoded_file_content_as_bytes.decode('ascii')

    language = 'ca'
    client.upload_file(project.project_id, {
        "data": base64_encoded_file_content,
        "filename": my_file_path,
        "lang_iso": language
    })
```
For what it's worth, I also tried with `language = 'cat'` and the result is the same.

**Expected behavior**
I expect to be able to upload a catalan translation file without error.

**Your environment:**
 -> docker (python:3.9.1-buster)
 pip install python-lokalise-api

**Additional context**
Don't hesitate to ask if you think I forgot something important.

**Comment by mathieudebrito** [comment]
Actually, it may come from the encoding of the content of file.
Is it possible to simply give the file path to the client

**Comment by bodrovis** [comment]
Hello! I'm sorry you are having troubles :( Could you please check whether your Lokalise project has Catalan language added? It should be present in the top menu like it's shown here: https://i.imgur.com/f1XKqjB.png Thing is, if the language is not added to the project, the upload process for this language will fail.

**Comment by mathieudebrito** [comment]
Thank you @bodrovis, this was the issue. I didn't know we must add the language before uploading the related files. And to be honest, the message did not help :p 
You saved me a few hours of tests, thanks again !

**Comment by bodrovis** [comment]
Glad it helped! Actually, I think we'll add more detailed explanations to the docs :+1:
