### ISSUE TITLE
Cannot get project info for branch

### ISSUE THREAD

**Issue by jaixan** [lokalise/python-lokalise-api#55]
In the documentation, it looks like you can access branch info like this :

> If you are using project branching feature in Lokalise, simply add branch name separated by semicolon to the project ID in any endpoint to access the branch, i.e. 3002780358964f9bab5a92.87762498:feature/new-release.

When I try to do this, I get an invalid project id parameter.

Is there a way to get statistics for a branch of a project language?

**Comment by bodrovis** [comment]
Could you please send me the code you're trying to use?

**Comment by bodrovis** [comment]
For example, here's how you can work with branches and processes: https://github.com/lokalise/python-lokalise-api/blob/b66008b7154f20936110b299469290024f387ac5/tests/client/queued_processes_test.py#L15 Basically, this approach will be the same in all other cases

**Comment by jaixan** [comment]
Here is the code that's failing 

```
project = client.project(f"{PROJECT_ID}:sandbox")    
print(project.statistics['languages'][1]['progress'])  
```
I get this error :  

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/lokalise/client.py", line 691, in project
    raw_project = self.get_endpoint("projects"). \
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/lokalise/endpoints/base_endpoint.py", line 59, in find
    return request.get(self.client, path, params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/lokalise/request.py", line 38, in get
    return respond_with(requests.get(__prepare(BASE_URL + path),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/lokalise/request.py", line 114, in respond_with
    respond_with_error(data, response.status_code)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/lokalise/request.py", line 129, in respond_with_error
    raise errors.ERROR_CODES[code](msg, code)
lokalise.errors.BadRequest: ('Invalid `project_id` parameter', 400)

```

**Comment by bodrovis** [comment]
@jaixan I just tested this feature and it does not work for me either. However, it has nothing to do with Python SDK - I tried cURL and get the same result. I'll get in touch with the guys who take care of the API itself and we'll work on this issue asap. I'll let you when there's a progress. You can also contact our support directly via lokalise.com site (there's a chat widget in the bottom right corner) if you have other questions in the meantime!

**Comment by bodrovis** [comment]
I've briefly checked with the team and it does not seem "Project" endpoint supports the branch suffix at the moment.. I'll try to get more info and understand whether it's an expected behaviour

**Comment by jaixan** [comment]
Thanks for all your help! Do you know another way to get progress from the langage of a branch by any other means? I'm looking to find if I have translations to do in the sandbox branch.

**Comment by bodrovis** [comment]
I'm waiting for a more detailed response from the team to understand whether it's possible or not - I'll try to provide some more info asap

**Comment by bodrovis** [comment]
So, unfortunately this is not possible at the moment :( However, the team has added this feature to the pipeline and is planning to work on it during the upcoming sprint, so everything goes smoothly, the fix should be released soon. The changelog will be updated accordingly on this page https://app.lokalise.com/api2docs/curl/#resource-changes Once again, feel free to reach out to our support team if you have further questions!
