### ISSUE TITLE
Any plan for asyncio support ?

### ISSUE THREAD

**Issue by alk-sramond** [lokalise/python-lokalise-api#75]
The feature I'd like is an asyncio version of the Lokalize client.

**Additional context**
When using asyncio in a python project is better to go full async vs mixing sync / async.

Thanks !

**Comment by bodrovis** [comment]
To be honest, I don't have any such plans at the moment. Wouldn't it be easier to somehow use this client in an existing project in an asynchronous way? Or I might be missing a point as I haven't worked with AsyncIO much.

**Comment by alk-sramond** [comment]
Hi, asyncio in our context is more to give back the hand to another handler (non threaded environment mono cpu) and avoid blocking the whole app just waiting for network i/o. (we are using fastapi)
The solution we think about was more or less the same client simply using aiohttp instead of request. Signature would be something like: `await client.upload_file`.

We might implement a few methods in the future we will let you know if we have an acceptable implementation.

**Comment by bodrovis** [comment]
Sure thing, don't hesitate to reach out to us if you have anything to showcase. I might spend some time on this as well but no promises - I have quite a lot of additional tasks at the moment :)
